/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ElButton: typeof import('element-plus/es')['ElButton']
		ElDropdown: typeof import('element-plus/es')['ElDropdown']
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
		ElForm: typeof import('element-plus/es')['ElForm']
		ElFormItem: typeof import('element-plus/es')['ElFormItem']
		ElIcon: typeof import('element-plus/es')['ElIcon']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElTooltip: typeof import('element-plus/es')['ElTooltip']
		HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
		IEpPlus: typeof import('~icons/ep/plus')['default']
		LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
	}
}
